#!/bin/bash

case "$0" in
	(/*) scriptdir="$(dirname "$0")";;
	(*)  scriptdir="$(pwd)/$(dirname "$0")";;
esac

use_jq_stack() {
	JQ_STACK_MODDIR="$scriptdir/deps/jq-mods/lib"

	. "$scriptdir/deps/jq-helpers/lib/jq_stack.lib.sh"
	. "$scriptdir/deps/jq-helpers/lib/jq_stack_modcall.lib.sh"
	. "$scriptdir/deps/jq-helpers/lib/jq_stack_modload.lib.sh"
	. "$scriptdir/deps/jq-helpers/lib/jq_stack_oneline.lib.sh"

	#. "$scriptdir/deps/jq-mods/jqf.lib.sh"

	jqf() {
		jq_stack modcall "$@"
	}
}

while [ $# -gt 0 ]; do
	case "$1" in
	('-s') shift;set -- --use jq_stack "$@" ;;
	esac
	case "$1" in
	('--use') shift
		if [ $# -gt 1 ]; then
			"use_$1"
		else
			echo >&2 "ERROR: --use missing argument"
			exit 1
		fi
	;;
	('-l'|'--list')
		(	cd "$scriptdir/mods/conv" &&
			ls -d1 */*.mod.sh |sed -e 's,\.mod\.sh$,,g' | sort
		)
		exit 0
	;;
	('-w'|'--write') CONV_WRITE=true;; # use for json_ff/flatfiles
	('--') shift; break ;;
	('-*') echo >&2 "ERROR: invalid option"; exit 1 ;;
	(*) break
	esac
	shift
done

if [ $# -eq 0 ]; then
	echo >&2 "Usage: conv [<options>] <fmt1>/<fmt2>[/<fmt3>[/...]] [args...]"
	exit 1
fi

_conv() {
	while [ $# -gt 0 ]; do
		case "$1" in
		(rgrepn/json_dfv)  shift;set -- "rgrepn/json_dfnl/json_dfv" "$@" ;;
		(rgrepn/json_ff)   shift;set -- "rgrepn/json_dfnl/json_dfv/json_ff" "$@" ;;
		(rgrepn/flatfiles) shift;set -- "rgrepn/json_dfnl/json_dfv/json_ff/flatfiles" "$@" ;;
		(rgrepn/tsv) ;;
		esac
		case "$1" in
		(*/*/*)
			local a="${1%%/*}"
			local bc_="${1#*/}"
			local b="${bc_%%/*}"
			shift;
			set -- "${a}/${b}" "${bc_}" "$@"
			_conv "$@"
			return $?
		;;
		(*/*)
			local a="${1%%/*}"
			local b="${1#*/}"
			shift
			(
				RequireMod "conv/${a}/${b}"
				local name="${a}_to_${b}"
				"$name" "$@"
			) | (
				if [ $# -gt 0 ]; then
					_conv "$@"
				else
					[ -t 0 ] || cat
				fi
			)
			return $?
		;;
		esac
		shift
	done
}

RequireMod() {
	if [ -z "$scriptdir" ]; then
		echo >&2 "ERROR: scriptdir variable not defined"
		return 1
	fi
	if [ -z "$1" ]; then
		echo >&2 "ERROR: Require: missing argument"
		return 1
	fi
	. "${scriptdir}/mods/$1.mod.sh"
}

Deps() {
	local self="Deps"
	while [ $# -gt 0 ]; do
		if ! command >/dev/null 2>&1 -v "$1"; then
			echo >&2 "ERROR: ${self}: missing dependency (command $1)"
			return 1
		fi
		shift
	done
	return 0
}

_conv "$@"
